linters-settings:
  gocyclo:
    min-complexity: 25
  gocritic:
    disabled-checks:
      - hugeParam
      - exitAfterDefer
      - ifElseChain
      - filepathJoin

issues:
  exclude-rules:
    - text: "stutters; consider calling this"
      linters:
        - revive
    - path: _test\.go
      linters:
        - errcheck
