run:
  go: "1.24"

linters-settings:
  gocyclo:
    min-complexity: 70
  gocritic:
    disabled-checks:
      - hugeParam
      - exitAfterDefer
      - ifElseChain
      - filepathJoin

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - revive
    - gocritic

issues:
  exclude-rules:
    - text: "stutters; consider calling this"
      linters:
        - revive
    - path: _test\.go
      linters:
        - errcheck
